---
- hosts: localhost
  become: yes
  become_methot: sudo
  vars_files:
  - some_region.yaml 
  tasks:
  - name: Say hello
    package:
      name: "{{package_name}}" 
      state: "{{state}}"
      # taking notes

