---
- hosts: localhost       #localhost do only in your machine            
  tasks:

  - name: create key pair using provided key_material          
    ec2_key:
      name: bastion_host
      region: us-east-1
     #state: absent
      key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQjg4LJlZtJRnyiz2GXqs8uHx88BN284Rtbut1zz5zWJuJ4FId8pSpi1eW3b/yWz9R1PX3B0EloZykNfRiyL3qkA7yO0BR1ieDJTlUkDxPCvunYdgsHyDK7d8Q1g/mFIms1jHauDLT5TjGEJxifWUahw3ST5D1Whk9MGDnZHyDFDEVWs/s56rd0BzL6n9zAL6X5shsqynQXgJe6/kINaBazxxdmQ13xppCQ94Y9/Sm/qv4PHgwKlwVXxx0CsDMdR1teW1BQznvKhIxDSlttXMZIbmZPyyLq088rjiaLwI2ALHoX8krdSOWhrp9Hrr078ueYJeFY2r7ZAlcS5CY0csB ec2-user@ip-172-31-21-239.eu-west-2.compute.internal'                                                                                                                                                                                                                                                